-- AlterTable
ALTER TABLE "ExtraItemCatalog" ALTER COLUMN "id" DROP DEFAULT,
ALTER COLUMN "updatedAt" DROP DEFAULT;

-- AlterTable
ALTER TABLE "ExtraShoppingItem" ALTER COLUMN "id" DROP DEFAULT,
ALTER COLUMN "updatedAt" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Ingredient" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Recipe" ALTER COLUMN "id" DROP DEFAULT,
ALTER COLUMN "updatedAt" DROP DEFAULT;

-- AlterTable
ALTER TABLE "ShoppingState" ALTER COLUMN "id" DROP DEFAULT,
ALTER COLUMN "updatedAt" DROP DEFAULT;

-- AlterTable
ALTER TABLE "WeekIndex" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "WeekPlan" ALTER COLUMN "id" DROP DEFAULT,
ALTER COLUMN "updatedAt" DROP DEFAULT;

-- AlterTable
ALTER TABLE "WeekPlanEntry" ALTER COLUMN "id" DROP DEFAULT;
